# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    container_name: mysql_container
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: APP_SNCF
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    container_name: adminer_container
    image: adminer
    restart: always
    ports:
      - 8080:8080