# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: utilisateur
      MARIADB_PASSWORD: utilisateur
      MARIADB_DATABASE: SNCF
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080