# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    container_name: mysql_container
    image: mysql:8.3.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: APP_SNCF
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - 3306:3306

  adminer:
    container_name: adminer_container
    image: adminer
    restart: always
    ports:
      - 8080:8080